
variables:
  WINDOWS_CMAKE_IMAGE: cunity/windows-1803-cmake:latest

.cunit-build-template: &cunit-build
  script:
    - |
      mkdir cmake-build
      cd cmake-build
      cmake ..
      cmake --build . -- -j4
      ./CUnit/Sources/cunit_test
      ./Examples/AutomatedTest/t-automated
      junit2html --summary-matrix TestAutomated-Results.xml

cunit-ubuntu-18.04:
  <<: *cunit-build
  image: registry.gitlab.com/cunity/linux-cmake-builders/ubuntu-18.04:master

cunit-ubuntu-17.10: 
  <<: *cunit-build
  image: registry.gitlab.com/cunity/linux-cmake-builders/ubuntu-17.10:master

cunit-win1803-vs2015:
  tags:
    - cunity-windows-docker-1803
  script:
    - $cwd = $(pwd).Path
    - docker pull $Env:WINDOWS_CMAKE_IMAGE
    - docker run -v $("$cwd" + ":c:\build:rw") -w c:\build\ --rm $Env:WINDOWS_CMAKE_IMAGE VS2015\build-x64.bat