
build_ubuntu_cmake:
  image: ubuntu:17.10
  script:
    - |
      apt-get update
      apt-get -y install cmake build-essential gcc libncurses5-dev python-pip
      pip install junit2html
      mkdir cmake-build
      cd cmake-build
      cmake ..
      cmake --build . -- -j4
      ./CUnit/Sources/cunit_test
      ./Examples/AutomatedTest/t-automated
      junit2html --summary-matrix TestAutomated-Results.xml
